# Generated by Django 4.1.4 on 2022-12-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_display',
            field=models.BooleanField(default=True),
        ),
    ]
